apiVersion: apps/v1
kind: Deployment
metadata:
  name: alec-buchanan-demo-v${VERSION}
  namespace: default
  labels:
    app: gh-aks
    version: "${VERSION}"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gh-aks
      version: "${VERSION}"
  template:
    metadata:
      labels:
        app: gh-aks
        version: "${VERSION}"
    spec:
      containers:
      - name: gh-aks
        imagePullPolicy: Always
        image: "alecbuchanan.azurecr.io/alec-buchanan-demo:${VERSION}"
        env:
          - name: SECRET_KEY
            value: dummy
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 128Mi

---
apiVersion: v1
kind: Service
metadata:
  name: alec-buchanan-demo-entrypoint
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: gh-aks
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: my-np-service
spec:
  type: NodePort
  selector:
    app: gh-aks
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
