apiVersion: apps/v1
kind: Deployment
metadata:
  name: alecbuchanan-cci-v${VERSION}
  namespace: default
  labels:
    app: cci-eks
    version: "${VERSION}"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cci-eks
      version: "${VERSION}"
  template:
    metadata:
      labels:
        app: cci-eks
        version: "${VERSION}"
    spec:
      containers:
      - name: cci-eks
        imagePullPolicy: Always
        image: "377117578606.dkr.ecr.us-west-1.amazonaws.com/alecbuchanan-cci:${VERSION}"
        env:
          - name: SECRET_KEY
            value: dummy
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 128Mi

---
apiVersion: v1
kind: Service
metadata:
  name: alecbuchanan-cci-entrypoint
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: cci-eks
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: my-np-service
spec:
  type: NodePort
  selector:
    app: cci-eks
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
