name: set-build-env
runs:
  using: composite
  steps:
  - uses: actions/checkout@v3.3.0
  - name: Setup Build Environment Variables
    run: |-
      echo "export VERSION=$(cat VERSION)" >> $BASH_ENV
      source $BASH_ENV
    shell: bash